### ISSUE TITLE
Project Review

### ISSUE THREAD

**Issue by SidTheEngineer** [adamwinzdesign/teaCozy#1]
### Criteria 1: HTML Structure  
* _Score Level:_ 3.5/4
* _Comment(s):_ Overall nice work with your HTML. The structure/formatting looks solid and the classes that are set up enables proper use of flexbox throughout. A couple of minor areas for improvement that I noticed include making sure indentation is good throughout (check out lines 65-68) and double checking that we use id's for our navigation links to link to (`href="#mission"` for example, means that when clicked, it will take the user to the element that has an id of "mission").
 
### Criteria 2: Visual Layout
* _Score Level:_ 4/4
* _Comment(s):_ The visual layout of the site is pretty much spot on with the design specification (including font/sizing and a sticky header at the top). Nice job here!
 
### Criteria 3: Use of Flexbox
* _Score Level:_ 4/4
* _Comment(s):_ Flexbox is the primary way of grouping elements throughout the site. Nice job working through containers and grouping each section of the page correctly!
 
### Criteria 4: Implementation of Design Specification and Content
* _Score Level:_ 4/4
* _Comment(s):_ All of the content and styling throughout the site matches that of the design specification, including colors, font, images, etc. I didn't see any issues in this regard 👍 
 
### Overall Score: 15.5/16 🔥 
With a minor adjustment to the way the navigation links are set up, this project is pretty much perfect! Great work using flexbox throughout the page and grouping items according to the spec without issues.

**Comment by adamwinzdesign** [comment]
Thanks, I will definitely get the links corrected.  I appreciate the feedback!
